In [1]:
import numpy as np

In [17]:
#1. Create a numpy array with a range of 6 elements
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [22]:
#2. Create a numpy array using list with 2 axes
b = np.array([["Name1","Name2","Name3"],["Id1","Id2","Id3"]])
print(b)

[['Name1' 'Name2' 'Name3']
 ['Id1' 'Id2' 'Id3']]


In [23]:
#3. Shape of numpy array b
b.shape

(2, 3)

In [24]:
#4. Access element of the array
print(b[0])

['Name1' 'Name2' 'Name3']


In [21]:
#5. Access the element of a 2D array
print(b[0][0])

Name1


In [25]:
#.6 Create an array with zeros
c = np.zeros(10)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
#7. Create a numpy array with ones
d = np.ones(10)
print(d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [30]:
#8. Create an array of definining the start and end range along with steps
e = np.arange(5,51,5)
print(e)

[ 5 10 15 20 25 30 35 40 45 50]


In [37]:
#9. Create a linearly spaced array, the bigger the number specified in num=? the bigger the array will spread into
f = np.linspace(0,10,num=10)
print(f)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [42]:
#10. Sorting an array of numbers
g = np.array([10,51,1,0,7])
g = np.sort(g)
print(g)

[ 0  1  7 10 51]


In [43]:
#11. Sorting an array of alphabets
g = np.array(["b","z","a"])
g = np.sort(g)
print(g)

['a' 'b' 'z']


In [57]:
#12. Concatenate two numpy arrays and sort them
arr1 = np.array(["a","b","c","d"])
arr2 = np.array(["z","e","f","p"])
arr3 = np.concatenate((arr1,arr2),axis=0)
arr3 = np.sort(arr3)
print(arr3)

['a' 'b' 'c' 'd' 'e' 'f' 'p' 'z']


In [64]:
#13. Dimension of an array
np_dim = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("Dimensions or axes", np_dim.ndim)

Dimensions or axes 2


In [66]:
#14. Size of the array is the elements in array
print("Size of the array is", np_dim.size)

Size of the array is 12


In [67]:
#15. Shape of the array
print("Shape of the array is", np_dim.shape)

Shape of the array is (4, 3)


In [71]:
#16. Reshape the array into 3,4
print("Before Reshape")
print(np_dim)
np_dim = np_dim.reshape(3,4)
print("After Reshape")
print(np_dim)

Before Reshape
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
After Reshape
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [76]:
#17. Another way to reshape
print("Before Reshape")
print(np_dim)
print("After Reshape")
print(np.reshape(np_dim, newshape=(2,6),order='C'))

Before Reshape
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After Reshape
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [96]:
#18. Add new axis to an array
arr1 = np.array([1,2,3,4,5,6])
print(arr1, arr1.shape)

print("First element:", arr1[0])

print("Adding an axis")
arr1 = arr1[np.newaxis]
print(arr1, arr1.shape)

print("First element:", arr1[0][0])

print("Adding an another axis")
arr1 = arr1[np.newaxis]
print(arr1, arr1.shape)

print("First element:", arr1[0][0][0])

[1 2 3 4 5 6] (6,)
First element: 1
Adding an axis
[[1 2 3 4 5 6]] (1, 6)
First element: 1
Adding an another axis
[[[1 2 3 4 5 6]]] (1, 1, 6)
First element: 1


In [100]:
#19. Slicing an array from and to range
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1[0:4])

[1 2 3 4]


In [101]:
#20. Slicing an array from to end
print(arr1[4:])

[ 5  6  7  8  9 10]


In [128]:
#21. Slicing more than ranges where value is greater than 5
arr1 =  np.array([[1,2,3,4],[15,25,15,45],[10,12,13,14]])
arr1[arr1 > 10]

array([15, 25, 15, 45, 12, 13, 14])

In [125]:
#22. Show the reuslt of a condition on the array
condition = (arr1 > 5) | (arr1 == 5)
print(condition)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [130]:
#23. Slicing based on calculation
print(arr1[arr1*2 > 1])

[ 1  2  3  4 15 25 15 45 10 12 13 14]


In [149]:
#24. Get indices of elements based on condition
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
result = np.nonzero(a > 6)
result

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [150]:
#25. Add an array with ones array
a = np.array([1,2,3,4])
b = np.ones(4)
print(a+b)

[2. 3. 4. 5.]


In [156]:
#26. Add two arrays
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[5,6,7,8],[9,2,2,4]])
print(a+b)

[[ 6  8 10 12]
 [10  4  5  8]]


In [160]:
#27. Sum elements of an array
a = np.array([1,2,3,4,5,6,7,8,9])
print(a.sum())
#or
print(np.sum(a))

45
45


In [170]:
#28. Sum a specific axis
a = np.array([[1,1,1,1],[1,1,1,1]])
print(a.sum(axis=1))

[4 4]


In [173]:
#29. Sum an axis and keep the dimensions
a = np.array([[1,1,1,1],[1,1,1,1]])
print(a.sum(axis=1,keepdims=True))

[[4]
 [4]]


In [174]:
#30. Sum a value to each array element
a = np.array([1,1,1,1])
print(a+2)

[3 3 3 3]


In [175]:
#31. Multiply a value to each array element
a = np.array([1,1,1,1])
print(a*2)

[2 2 2 2]


In [176]:
#32. Find the max number in an array
a = np.array([[1,2,3,4],[8,7,55,3]])
print(a.max())

55


In [178]:
#33. Find the min number in an array
a = np.array([[-1,2,3,4],[8,7,55,3]])
print(a.min())

-1


In [181]:
#34. Min or Max on an axis
a = np.array([[-1 ,2 ,3  ,4],
              [ 8 ,7 ,55 ,3]])
print(a.min(axis=0))
print(a.min(axis=1))
print(a.max(axis=0))
print(a.max(axis=1))

[-1  2  3  3]
[-1  3]
[ 8  7 55  4]
[ 4 55]


In [183]:
#35. Slicing matrices, First element of the first row 
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [11,22,33,44]])

print(a[0,0])

1


In [190]:
#36.Slice the second row
print(a[1:2])

[[5 6 7 8]]


In [191]:
#37. Slice first elenent of each row
print(a[0:3,0])

[ 1  5 11]


In [212]:
#38. Random number generation
a = np.random.rand(100)
print(a)

[0.54184025 0.91547787 0.56018811 0.33127799 0.32838834 0.21566033
 0.51538869 0.88929582 0.98840687 0.83610617 0.07363846 0.58456128
 0.61611168 0.01085356 0.59008017 0.88799232 0.39131445 0.59404022
 0.25048227 0.01263337 0.63960488 0.44147713 0.20565108 0.37131038
 0.66463531 0.65224248 0.63236928 0.76071696 0.67867512 0.05348455
 0.33878156 0.08239528 0.11114619 0.14560834 0.75258225 0.31187506
 0.32464713 0.41175423 0.31942159 0.11840581 0.77752409 0.07425956
 0.0912467  0.65143148 0.08108152 0.17885572 0.02359984 0.36983029
 0.16548214 0.53394962 0.8258373  0.58215646 0.70598014 0.95981474
 0.93858295 0.8834686  0.99278658 0.00386152 0.98271079 0.48583759
 0.98482664 0.14183816 0.39639007 0.18982165 0.08171478 0.64611016
 0.35606603 0.62421971 0.09933424 0.72658746 0.52962486 0.87723364
 0.04689999 0.98784976 0.65993839 0.31700811 0.18044452 0.67140531
 0.89408813 0.34746556 0.60306226 0.51446374 0.70288766 0.4496529
 0.02261395 0.04940376 0.2434413  0.70068645 0.24130714 0.65278

In [219]:
#39. Random integer numbers withing a specified range
a = np.random.randint(0,10000000,10)
print(a)

[ 646698 8200888 2659105 1247136 5257655 3633491 2609034 2075386 1631079
  597118]


In [227]:
#40. Fetch unique numbers from an array
a = np.array([[10,12,12,13,14,15,15,15,15],
              [21,21,22,23,24,25,25,25,85]])
print(np.unique(a))

[10 12 13 14 15 21 22 23 24 25 85]


In [228]:
#41. Fetch unique numbers from an array at a particular axis
print(np.unique(a,axis=1))

[[10 12 12 13 14 15 15]
 [21 21 22 23 24 25 85]]


In [236]:
#42. Fetch the unique numbers and indecies of the unique elements
unique_nums = np.unique(a,return_index=True) #Returns a tuple with numbers and indices
print('Numbers',unique_nums[0])
print('Indices',unique_nums[1])

Numbers [10 12 13 14 15 21 22 23 24 25 85]
Indices [ 0  1  3  4  5  9 11 12 13 14 17]


In [246]:
#43. Transpose an array
a = np.array([[1,2,3,4],
              [1,2,3,4]])
print(a.transpose())

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [249]:
#44. Reverse an array
a = np.array([1,2,3,4,5,6])
print(np.flip(a))

[6 5 4 3 2 1]


In [292]:
#45. Reverse a 2D array
a = np.array([[1,2,3,4],
              [7,8,9,10]])
a= np.flip(a,axis=0)
print(a)

[[ 7  8  9 10]
 [ 1  2  3  4]]


In [293]:
#46. Reverse only the second column
print(a[:,1])
a[:,1] = np.flip(a[:,1])
print(a[:,1])
print(a)

[8 2]
[2 8]
[[ 7  2  9 10]
 [ 1  8  3  4]]


In [294]:
#47. Flip the second row only
a[1,:]= np.flip(a[1,:])
print(a)

[[ 7  2  9 10]
 [ 4  3  8  1]]


In [299]:
#48. Flatten a multidimensional array
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [301]:
#49.Square of an array
print(np.square(a))

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [303]:
#50. Round an array
a = np.array([1.1,2.4,5.6,7.10])
print(np.round(a))

[1. 2. 6. 7.]
